name: CI

on: [push, pull_request]

jobs:
  run:
    name: "Build using Racket (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-variant: ["BC", "CS"]

    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.7
      with:
        distribution: 'full'
        version: stable
        variant: ${{ matrix.racket-variant }}
    - run: raco pkg install --batch --auto --link --name yaragg
    - run: xvfb-run raco test --drdr --package yaragg
